apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartement-calc-streamlit-deployment
  labels:
    app: ac-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-streamlit
  template:
    metadata:
      labels:
        app: ac-streamlit
    spec:
      containers:
        - name: ac-streamlit
          image: peterzwegat1997/wohnungspreisschaetzer-leipzig:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ac-streamlit-service
spec:
  selector:
    app: ac-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
